version: '3'
services:
  apienrutador:
    build: "api_enrutador/."
    ports:
      - "7071:8080"
    networks: 
      - "service-docker"
  apipresentacion:
    build: "api_presentacion/."
    ports:
      - "7072:9999"
    networks: 
      - "service-docker"
  apidespachador:
    build: "api_despachador/."
    ports:
      - "7073:9998"
    networks: 
      - "service-docker"
  apitransformacion:
    build: "api_transformacion/."
    ports:
      - "7074:9997"
    networks: 
      - "service-docker"
networks:
  service-docker:
    driver: bridge
