version: '3'
services:
  apienrutador:
    build: "api_enrutador/."
    ports:
      - "9091:8080"
    networks: 
      - "service-docker"
  apipresentacion:
    build: "api_presentacion/."
    ports:
      - "9092:9999"
    networks: 
      - "service-docker"
  apidespachador:
    build: "api_despachador/."
    ports:
      - "9092:9999"
    networks: 
      - "service-docker"
  apitransformacion:
    build: "api_transformacion/."
    ports:
      - "9093:9998"
    networks: 
      - "service-docker"
networks:
  service-docker:
    driver: bridge
